services:
  - type: web
    name: blog-site
    env: python
    buildCommand: pip install -r OneDrive/Desktop/blog_site/requirements.txt

    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
